title: ePortfolio
description: CS-499 Computer Science Capstone by Faizah
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
github:
  zip_url: https://www.google.com
  tar_url: https://mothership.sg
  repository_url: https://www.wikipedia.org
